### ISSUE TITLE
header.phpのviewportの部分について

### ISSUE THREAD

**Issue by hidekichi** [yhira/simplicity2#1]
もしかしたら僕が以前のバージョンをカスタマイズして勘違いしていたのかも知れませんけれども、header.phpの[viewport](https://github.com/yhira/simplicity/blob/master/header.php#L14)なんですが、

``` php
<?php //ビューポート
//モバイルもしくはページキャシュモードの時
if ( is_mobile() || is_page_cache_enable() ): ?>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
<?php else: ?>
```

このifの中に、`is_responsive_enable()`が含まれている必要があるのではなかろうかと思ったりなんちゃったり。
完全レスポンシブの時は、viewportがdevice-widthだった気がするんですけれども、違いましたでしょうか？
現在のheader.phpの[viewport](https://github.com/yhira/simplicity/blob/master/header.php#L14)だと、完全レスポンシブがonの時にmobile.cssが読み込まれないと言うような状態で、viewportが1280とかになると、ややこしいことになるのではなかろうかとふと思ったりしたので報告します。

実験的に現在Simplicity2の最新版をサイトに適用して、最新scssから出力したcssも適用した状態にしています。ここで完全レスポンシブをonにして上記ソースのif文に`is_responsive_enable()`を追加してviewportをdevice-widthにしていますが、特別問題は起きないようです。

**Comment by yhira** [comment]
そのようにしたほうがよさそうですね。
修正しておきました。ありがとうございます！
完全レスポンシブモードは、あまり使わないので、今回見直してみたら他にも結構具合のありました；
